[package]
name = "mc-rs-plugin-lua"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-rs-plugin-api = { path = "../mc-rs-plugin-api" }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
